
[general]
app_name = "V V V V"
debug = true

[theme]
primaryColor="#1b4332"
backgroundColor="#fff"
secondaryBackgroundColor="#e9ecef"
textColor="#000"
font="sans serif"


[client]

# Whether to enable st.cache.
# Default: true
caching = false


[logger]

toolbarMode = "developer"